### ISSUE TITLE
Always getting PubnubException

### ISSUE THREAD

**Issue by Zein765** [Frizz925/StarlightStageSpoofer#1]
Hello, i am trying to build a spoofer server. And everything is going well until when i trying to open it on web browser.
The page always show a blank page, and after i look at the response it seems there is something wrong on pubnub.php (http response : 500) 

and after i open dist/pubnub.php, it always said "PubnubException in Pubnub.php line 93: Missing required $subscribe_key param"
and after some searching, i found that i need to get a pub_key and sub_key, now for the question, what should i do to fix this error? how to init the pubnub?

**Comment by Frizz925** [comment]
You should set PUBNUB_PUBLISH_KEY and PUBNUB_SUBSCRIBE_KEY in the .env file. I've updated the example file to include it.
