### ISSUE TITLE
Network connection error

### ISSUE THREAD

**Issue by yuitti1114** [Frizz925/StarlightStageSpoofer#3]
Hello, thank you for publishing the project.
This is very informative, I’ve learnt a lot from it.

I changed the hosts file, but a network connection error appeared on the startup.
I'd like to know whether the DNS server address is correct.
Is there a possibility that it was changed?
Or has it already been taken measures by Cygames?

![screenshot](https://cloud.githubusercontent.com/assets/3735741/21183627/24b6cc3e-c24c-11e6-82ba-2030bb62c2a0.png)

**Comment by Frizz925** [comment]
I moved my server along with the domain name to somewhere else since a month ago. It's still indefinite when I will host the spoofer server again but feel free if you want to host your own server.

**Comment by yuitti1114** [comment]
I see, so what you're saying is that I have to build the spoofer server and rewrite the DNS addresses to new one?
I would be grateful if you could show the procedure in breef.
