### ISSUE TITLE
RuntimeException in compiled.php line 7746: No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by NyanRa** [Frizz925/StarlightStageSpoofer#4]
Hi. i try to install the spoofer, but when i try to open it gives me error like this
![error 1](https://cloud.githubusercontent.com/assets/11331257/23703393/4e27839c-0432-11e7-8d3f-c2ab16de1d1c.png)
![error 2](https://cloud.githubusercontent.com/assets/11331257/23703395/5309cd48-0432-11e7-8af4-f4fbe89cddb7.png)

Thanks!

**Comment by Frizz925** [comment]
Have you created the ,env file? Create one and then generate the app key using "php artisan key:generate"

**Comment by NyanRa** [comment]
Hi. I had try using php artisan key:generate. But now it just give me blank page.

**Comment by Frizz925** [comment]
What's the content of your env file

**Comment by NyanRa** [comment]
Hi, sorry for late reply
This is my env 
![env](https://cloud.githubusercontent.com/assets/11331257/24881043/c3e6705e-1e66-11e7-9c6d-4e5711608658.png)
And the blank page
![blank](https://cloud.githubusercontent.com/assets/11331257/24881059/cf4d69d4-1e66-11e7-8c6a-d8d911369914.png)
Thanks.

**Comment by Frizz925** [comment]
Can you check your browser console?

**Comment by Frizz925** [comment]
Closing this since no reply for 14 days. The problem may as well be with improper steps taken in setting up the application.
