### ISSUE TITLE
Trying to understand how to decode a MessagePacked response

### ISSUE THREAD

**Issue by izy521** [Frizz925/StarlightStageSpoofer#5]
Hello, thank you for the project, I've been messing around with Deresute for a project I'm doing and I'd like to ask you how you managed to decode the request/responses. I apologize if this doesn't have anything directly to do with the project. If there's somewhere else you'd like this discussed, I can move.

I'm looking through your code and some places have me confused, like how you have both the  [AES256Crypt](https://github.com/Frizz925/StarlightStageSpoofer/blob/7c09530e06ddbdd3db67bf897973f4d58d0d1271/local/laravel/src/Spoofer/AES256Crypt.php#L5) and [Encryption](https://github.com/Frizz925/StarlightStageSpoofer/blob/7c09530e06ddbdd3db67bf897973f4d58d0d1271/local/laravel/src/Spoofer/Encryption.php#L7) classes, each using a different key. And [here](https://github.com/Frizz925/StarlightStageSpoofer/blob/7c09530e06ddbdd3db67bf897973f4d58d0d1271/local/laravel/app/Http/Controllers/SpooferController.php#L72) you call `Encryption::decrypt` which decodes base64 data within it, but you also decode base64 data afterwards, is it double-encoded?

I'm trying a Node.js method of decrypting the data. I've received it via MITMProxy as base64 and saved it as a binary. I've attempted to use both keys to decrypt it but I'm just getting errors, so I thought I may ask you what the exact process is for doing this.

Thank you in advance.

**Comment by Frizz925** [comment]
It's double Base64-encoded with Msgpack and AES256 encryption in-between. To fully decrypt it into parseable Msgpack byte-string, you need to do the following.

1. Base64 decode the original string to get the encrypted byte-string. We'll call this the "encrypted" string.
2. Decrypt it using MCRYPT_RIJNDAEL_256 with the key taken from the last 32 characters of the "encrypted" string and the IV taken from UDID inside the HTTP request/response headers (the UDID is obfuscated, you can check how to restore it from the [Cryptographer](../tree/master/local/laravel/src/Spoofer/Cryptographer.php) class).
3. The decrypted string is still Base64-encoded and this is where the second Base64 decoding takes place. 
4. The decoded string can now be parsed by Msgpack parsers.

**Comment by izy521** [comment]
Thank you very much. Just to double-check, the KEYSTR string `s%5VNQ(H$&Bqb6#3+78h29!Ft4wSg)ex` is not used in this process at all?

**Comment by Frizz925** [comment]
That hardcoded key is used to decrypt some sort of parameter from the HTTP headers. [Look here](blob/master/local/laravel/app/Http/Controllers/SpooferController.php#L104).
